### ISSUE TITLE
Clarification needed about loading in-extension modules from injected scripts

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#10]
[This section](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-JavaScript-Injection) says:

>  the registered JavaScript file ...  will be executed in the old "legacy" privileged scope.

I think it's important to clarify whether such a script is then able to load modules from other JS files within the extension's content folder, e.g.:
```
var { foo, bar } = ChromeUtils.import("chrome://myext/content/myext-common.js");
```

**Comment by jobisoft** [comment]
Is this now more obvious, or does it need explicit mentioning?

**Comment by eyalroz** [comment]
It's too bad I can't make Wiki edits instead of filing all these issues...

Anyway, it's now obvious enough, but - I think it belongs in the text outside the code, not in a long comment. I might start a new subsection at the paragraph beginning with "The WindowListener API is not" - a section about the execution of the loaded 'subscripts. In that section I'd have the text about:

* Whether the file-level code get run or not
* When it gets run
* Whether multiple scripts know the code of previously-loaded scripts or are separated
* The auto-generated namespace
* The available global objects

**Comment by jobisoft** [comment]
Check 
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-JavaScript-Injection#scope-and-loading-of-other-javascript-files

Reopen if needed.

Thanks for your feedback and helping to make this guide better.

**Comment by eyalroz** [comment]
Thanks for not getting worn out by my endless nitpicking. Please don't hesitate to tell me if they become too burdensome / not productive.

**Comment by jobisoft** [comment]
I will :-)

I uploaded a new version of the API which actually supports the modified icon picking (16px default, but downscaled larger icons as fallback)
