### ISSUE TITLE
Clarification needed about file-scope code executin in injected scripts

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#11]
Some extensions' script files have some file-scope JS used for various initializations:
```
const Cc = Components.classes;
const Ci = Components.interfaces;
MyExt.__defineGetter__("ImapService", function() {
  delete MyExt.ImapService;
  return MyExt.ImapService = 
    Cc['@mozilla.org/messenger/imapservice;1'].getService(Ci.nsIImapService);
});
```
will this be executed when the JS file containing the above code is loaded with the line
```
Services.scriptloader.loadSubScript("chrome://myext/content/myext.js", this, "UTF-8");
```

Relates to #10 l

**Comment by jobisoft** [comment]
In the first example here:
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-JavaScript-Injection

I introduce the scriptloader and say it is a 1-to-1 replacement for the script tag. I think that answers your question? Do you want to have that mentioned somewhere else as well?

**Comment by eyalroz** [comment]
> I think that answers your question? 

It doesn't, because I interpreted that 1-to-1 comment to just mean that you need to have one injection line for every script element you had in your overlay file, and in the same order - nothing more.

> Do you want to have that mentioned somewhere else as well?

I think I would mention, below the example, that the file-scope code in each of the loaded "subscripts" will be executed. Perhaps it is also worth mentioning whether it is executed immediately when `loadSubscript()` is invoked, or at some later point.

**Comment by eyalroz** [comment]
Oh, also,, the injector script example calls a `QuickFolders.init()` function, while, supposedly, the scripts themselves would have whatever initialization code is necessary at file scope. That's another reasonf ro the need for a clarification.

**Comment by jobisoft** [comment]
I made changes. could you give feedback?

**Comment by eyalroz** [comment]
See [here](https://github.com/thundernest/addon-developer-support/issues/10#issuecomment-665858313).
