### ISSUE TITLE
onLoad() function example nitpick

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#12]
Issues with [this function](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-JavaScript-Injection#onload):

1. A closing back-tick is missing.
2. The parsed toolbar _button_ is named `toolbarpalette`. In fact it is added _to_ a toolbar palette.

**Comment by jobisoft** [comment]
fixed both and added a second style sheet.
