### ISSUE TITLE
onLoad() function example should have a slightly more complex XUL fragment 

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#13]
The current example for an `onLoad()` function injects a single XUL element as an arbitrary child of an existing parent element. Instead I think the example should have:

* At least two XUL elements (which in an overlay simply follow each other, but here probably need to be parsed and added separately)
* an `insertbefore` attribute, or perhaps even better - 
* an `insertafter` attribute

**Comment by eyalroz** [comment]
On that note - the example code parses a single `<html:link>` element for a CSS stylesheet, but calls the result "styles", plural. Does that mean that the result of parsing might be multiple DOM nodes? If not, why use the plural? If so,, that's relevant to the parsing of other elements obviously.

**Comment by eyalroz** [comment]
about insertafter... see also [this](https://thunderbird.topicbox.com/groups/addons/Td23710725b0ea61d/trouble-implementing-an-insert-after-for-an-extensions-overlay-injector).

**Comment by jobisoft** [comment]
I plan to add a `injectElements()` helper function, which can take a larger XUL fragment and parse its insertbefore="" and insertafter="" attributes and thus mimics the behaviour of the old overlayloader. I hope to have that ready by tomorrow. Just to give you a heads up, that if you want to use it you may wait a bit to not waste time...

**Comment by jobisoft** [comment]
This means that the XUL code from TB8 needs almost no changes and does not need to be split up in pieces.

**Comment by jobisoft** [comment]
I updated the guide and used a more complex example.
