### ISSUE TITLE
onUnload parameter semantics/naming confusing

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#14]
```
function onUnload(isAddOnShutDown)
```
So, when is `isAddOnShutDown` true? The name suggests that it's true when only the add-on is shutting down, and false if everything is shutting down. However, the function's implementation has this:
```
   // no need to clean up UI on global shutdown
  if (isAddOnShutDown)
      return;
```
which suggests the opposite. So, which is it?

**Comment by jobisoft** [comment]
Woah, something is indeed wrong there. The example is wrong for sure. But also the parameter itself is not enough. We can have:
- isAppShutdown (no need to cleanup anything, as Thunderbird is shutting down)
- isWindowClose (no need to cleanup UI, but maybe unregister stuff, like observers)
- isAddonShutdown (the Window is still open, while AddOn is shutting down, we need to cleanup the window UI)

It can only be one of those three, so I may need an  `unloadReason`.

Thanks for catching that.

**Comment by jobisoft** [comment]
or I use `isWindowClosing` and send true if the window is closing (either by the user or because Thunderbird is closing).

**Comment by jobisoft** [comment]
I returned to isAddonDeactivation in unload and isAddonActivation in load. Could you give feedback?

**Comment by eyalroz** [comment]
1. How about `isAddonActivationOnly` and `isAddonDeactivationOnly`?
2. Make sure you're consistent throughout your guide regarding the use of "extension" vs "add-on".
3.  Perhaps something like:

```
// Called whenever this add-on should load its content into the window.
//
// isAddonActivation: If true, the window is already loaded and it's
// just the add-on being activated; otherwise they're being loaded together.
```
and similarly for `onUnload()`

**Comment by jobisoft** [comment]
I introduce this now directly in the first section and not in a comment. Reopen if needed.
