### ISSUE TITLE
Followed all instructions for TB 68, but nothing happens

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#15]
I've followed the guide's instructions and adapted my extension accordingly (for TB 68, not 78 yet). I'm now trying to load it and use it with TB 68.10.0. While installation seems to succeed, and I see the extension as being installed - but with no effect. That is, no UI was injected and no error/warning messages that relate to the extension appear in the Error Console.

XPI: [removedupes_0.5b1_tbird.xpi.zip](https://github.com/thundernest/addon-developer-support/files/4997279/removedupes_0.5b1_tbird.xpi.zip) (had to add `.zip` to the name so GitHub would accept it).

**Comment by jobisoft** [comment]
I do not see an entry for a background script in your manifest.

**Comment by eyalroz** [comment]
Embarrassing.
