### ISSUE TITLE
Explain the XUL fragment parser's behavior for multiple XUL elements

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#17]
In the current example injector script, a XUL fragment is parsed which contains two elements, not within any container element. (It happens to be two html:link's for styles).

This is puzzling, since the code then applies `appendChild()` to the result - child, not children. If by some magic the parsing produces an array of elements, and appendChild can take an array, that would be pretty useful... and if that's not what happens then I don't quite understand what's going on...

So an explanation is in order IMHO.

**Comment by jobisoft** [comment]
Could you try to inspect a document you injected into and see what happened? I believe multiple elements can be added, but I cannot check currently.

**Comment by jobisoft** [comment]
Documentation of appendChild():
https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

As parseXULToFragment returns a DocumentFragment, all elements will be added.

**Comment by eyalroz** [comment]
Please reopen.

While this answers the question for me - the example in the guide, of the toolbarbutton, leads one to believe that the parsed XUL fragment should contain a single element, and the result is a single XUL element / DOM node - which as I now realize is not the case.

It's important that the example show at least _two_ elements, and that the variable name will make it clear the result isn't some container element for these elements, but a collection/sequence of elements. e.g. `paletteItems` or `itemsToInject`. Alternatively, the variable name could indicate that the parsing result is a document fragment, and a comment would clarify that the `appendChild()` will append all elements in the fragment.

**Comment by jobisoft** [comment]
1. The guide no longer uses `appendChild` but `injectElements`
2. It is your other issue that aksed for a more complex examples (and that is still open and I am working on that)
