### ISSUE TITLE
Need clarification regarding the use of an extra subfolder

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#2]
It has been customary  in many extensions (perhaps even necessary at some point) to structure the chrome directories with a suffix directory having the short name of the extension, e.g.: `chrome/locale/en-US/myext/` containing en-US locale for extension "myext".

In [this example](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisterchromeurl), such suffixes are not used. It would be useful if the text said something about this point, e.g. whether such a suffix is no longer necessary and can thus be dropped, or whether it was never necessary and is merely a matter of custom.

**Comment by jobisoft** [comment]
Can you point me to an example of such a chrome.manifest?

**Comment by eyalroz** [comment]
My own extensions... e.g.:

https://github.com/eyalroz/removedupes/blob/master/src/chrome.manifest

**Comment by jobisoft** [comment]
I use the same internal method to register the locale URLs as the manifest parser. So that should work. I am just not sure about the jar files. I think you have to drop that when doing the final switch over to TB78. Is there any benefit using jars?

**Comment by eyalroz** [comment]
I've just dropped them as a separate, initial phase on another branch.

I think the benefit was that you didn't have to install a large number of files. Extension installation used to be a lot more "DIY" back in the day - although right now we're deteriorating back towards that state of affairs. [This](https://github.com/eyalroz/removedupes/blob/master/src/install.js) is what you use to install remove dupes on Seamonkey 1.x. Note that it's a 13-year-old script of mine, and it's not even really mine, I copy-pasted and adapted it from somebody else; I'm sure something much better could be written instead.  But if you just wanted to work on your extension - not on extension installation infrastructure - you could make do with something like that.

**Comment by jobisoft** [comment]
I made changes, which I think cover your remarks.

**Comment by jobisoft** [comment]
Closing this, to have it out of the way. Reopen if needed.
