### ISSUE TITLE
messenger object in extension scope is somewhat confusing

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#23]
Before beginning an extension's conversion, `messenger` is a global object, which we use say, for the `.msgHdrFromURI()` method.

With the extension being relegated to a different scope, _that_ messenger is not available as an unqualified global, but rather as `window.messenger`. This is a bit inconvenient, but fine, since it easily triggers an error, and it's consistent with other window-scope variables.

However, you're adding a different kind of `messenger` object:
>`messenger`: A reference to the main MailExtension/WebExtension object. In Firefox this is called browser and in Google Chrome it is called chrome. It provides access to the MailExtension/WebExtension APIs, like messenger.storage.*. You probably do not need it in your first conversion step.

and that's not we need. It will also trigger errors in possibly confusing places, after we've ascertained the messenger is available and are trying to use it somehow. Please consider providing it under a different name (e.g. `mailExtensionMessenger`), or perhaps not at all.

**Comment by jobisoft** [comment]
did you see the reopened namespace issue of yours? I am currently rethinking this. If you could respond in the issue that would be helpful.

If your feedback is positive, I think about injecting into global window again and provide a global getMailExtensionStuff() which you can call to get the special objects, instead of a injecting them. This would get rid of namespace altogether.

**Comment by eyalroz** [comment]
Just read it now.

**Comment by jobisoft** [comment]
I moved the special objects and functions inside a `WL` object. So my `messenger` object is no longer interfering with the build in messenger object. That also means that injectCSS and injectElements are now reachable via WL.injectCSS and WL.injectElements.

I hope this solves this issue. Can you confirm, that the new version 1.12 is working as desired?

I also updated the wiki to describe the two different methods to load additional JS files. Feedback will be appreciated,

**Comment by eyalroz** [comment]
@jobisoft : So, it looks like you only moved the functions inside `WL` for the injector scripts, but not for `background.js`. It would be better if it would be accessible the same way from everywhere.

**Comment by jobisoft** [comment]
Hm, background.js Never had access to those objects. Can you give more details regarding your request?

**Comment by eyalroz** [comment]
I mean `messenger.WindowListener.whatever()` calls.

**Comment by jobisoft** [comment]
Those things have nothing in common. Background.js is running in WebExtension scope and the calls messenger.WindowListener.* are standard WebExtension syntax.

**Comment by eyalroz** [comment]
> Those things have nothing in common. 

They are:

* Javascript files,
* that are part of the extension,
* which invoke WindowListener methods.

Sounds like a lot in common to me...  :-P

**Comment by jobisoft** [comment]
But I cannot change the calls to a WE API as I can change the name of an standard js object which I add to some other object.

Can we consider this closed? Is your Add-On still running with WL 1.12?

**Comment by eyalroz** [comment]
Yeah, I guess.
