### ISSUE TITLE
Add-on Options vs Add-On Preferences

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#25]
In TB 68 (perhaps also later?) Extension/add-on preferences/options are accessed through: Tools | Add-On Preferences | NameOfExtensionHere. But - WindowOverlay puts the menu item under Add-On Options. Bug?

The window DOM has:
```
<menupopup id="addonPrefs_revived" hasbeenopened="true">
  <menuitem ... label="Remove Duplicate Messages (Alternate)">...</menuitem>
</menupopup>
```
and then:
```
<menupopup id="addonPrefs" onpopupshowing="initAddonPrefsMenu(this);" oncommand="openAddonPrefs(event.target.getAttribute('value'), event.target.getAttribute('optionsType'));" hasbeenopened="true">
... lots of stuff...
</menupopup>
```

**Comment by jobisoft** [comment]
In Windows that was always called add-on options. I saw that the original source had a different localization string for Linux, which i did not include and tend not to include. Are you in Linux?

**Comment by jobisoft** [comment]
Some more info: That menu does not exist at all in TB78, and the WindowListener revives it. In TB68 it will add a second Menu entry, as I do not want to mess/interact with the original one.

**Comment by eyalroz** [comment]
Yes, I am on Linux. Did someone actually use a different label on Windows and Linux? (facepalm)

**Comment by jobisoft** [comment]
https://searchfox.org/comm-esr68/source/mail/base/content/mainNavigationToolbox.inc.xul#950

Yes.

**Comment by eyalroz** [comment]
Oh, this is because the "Tools|Options" vs "Edit|Preferences" thing, right?

I never understood how that came to pass.
