### ISSUE TITLE
Consider adding text regarding platform-specific skin in non-injetcted XUL

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#27]
The guide currently tells you how to have your injections diverge depending on the platform, as an alternative to relying on `skin` being platform-specific. But - what about the use of `skin` styles (or scripts) from dialogs/windows which aren't injected? I've been having [troube](https://thunderbird.topicbox.com/groups/addons/Tb9b1ea36f66acfe7/loading-platform-dependent-skin-css) with that...

Now, I'm not sure whether that's even within the scope of the guide; but it might be - if the intent is to provide the information necessary for completing a conversion.

**Comment by jobisoft** [comment]
I tackled this from another angle. I now instruct developers to use the runtime API to evaluate the used OS and simply register the correct resource, so they can keep independent CSS files and this will then also work in windows which are not manipulated by the window listener.

https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisterchromeurl
