### ISSUE TITLE
Explose facility for checking browser version or choosing between XUL and XHTML

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#29]
Right now, I have:
```
messenger.WindowListener.registerOptionsPage("chrome://removedupes/content/removedupes-prefs.xhtml")
messenger.WindowListener.registerOptionsPage("chrome://removedupes/content/removedupes-prefs.xul")
```
and similarly for window registration etc. This is silly. Instead, I could write:
```
let xulSuffix = (versionIsAtLeast("69.0") ? "xhtml" : "xul");
messenger.WindowListener.registerOptionsPage("chrome://removedupes/content/removedupes-prefs." + xulSuffix)
```
... but for this I would need to obtain the version and compare versions. Trivial in a privileged context, not so trivial in browser.js . But - the WL can expose this for our use...

Another, perhaps better, alternative, is to have some sort of auto-conversion to XHTML, or an override for the document type from detection-by-extension. That would be even better, since I would not need to bundle copies of the same files twice.

**Comment by jobisoft** [comment]
In background you can use MailExtension API

await browser.runtime.getBrowserInfo();

https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo

But I do not suggest to make this multi version compatible. I will not support this as I consider that wasted time. Mine and yours.

**Comment by eyalroz** [comment]
@jobisoft : 

1. There's no example of that in the guide.
2. But then I have to parse the app info, extract the version string, split it by dots, and compare. And not just me, everyone who wants to do what I did above, which is, well, pretty much everybody.

**Comment by jobisoft** [comment]
This is beyond the scope of this guide. I will not have the time and resources to support it. Keep your TB68 version and release a new TB78 version. You can still update the older one, if you use different main branch version numbers. The effort to backport fixes is much less difficult than to go multiversion.
