### ISSUE TITLE
"The 16px icon defined in the manifest.json" <- what 16px icon?

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#3]
[This section](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisteroptionspage) says:

> The 16px icon defined in the `manifest.json` file will be used for the iconic menuitem.

What 16px icon? I've never defined one. The TB 68 update guide did suggest we define an icon section, but - I never did, any my icon was still used somehow. Also, the TB 68 example only had a 32-pixel icons defined.

Please:

* Clarify whether explicitly defining an icon is really necessary, or whether there's an implicit default
* Whether one needs a 16-px version of one's icon, or just the full size of whatever you have is good enough
* Link to [this page](https://developer.thunderbird.net/add-ons/updating/tb68/overlays) for an example on how to define the icon.

**Comment by jobisoft** [comment]
You do not have an icon defined in your manifest.json in your TB68 version of your AddOn? And it works? Maybe the icon is extracted from ATN?

I need an 16px icon and I assumed all AddOns should now have an icon section. I will add an example icon section.

**Comment by eyalroz** [comment]
> You do not have an icon defined in your manifest.json in your TB68 version of your AddOn? 

I don't. I don't have _any_ icon defined, actually.

> And it works?

Yes.

> Maybe the icon is extracted from ATN?

That's definitely possible.

> I need an 16px icon and I assumed all AddOns should now have an icon section. I will add an example icon section.

And are you sure a 32px icon won't cut it? i.e. it won't be scaled down?

**Comment by jobisoft** [comment]
I made changes, which I think cover your remarks.

**Comment by jobisoft** [comment]
Closing this, to have it out of the way. Reopen if needed.
