### ISSUE TITLE
Don't report a missing onUnload as an error

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#32]
Now that injected elements are auto-remoted on unload by WL itself, it is often/usually the case that the injector script's `onUnload()` is just empty.

I'd therefore consider checking whether an `onUnload()` function exists, invoking it if it does, and not report an error if it isn't found (at most - print a message when in debug mode).

**Comment by jobisoft** [comment]
done in https://github.com/thundernest/addon-developer-support/commit/af11a8f7688bdfcd6467a9db8a4871fb3d081fe1
