### ISSUE TITLE
Detect registration attempts of missing files/documents

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#38]
A common bug when adapting extensions to use the WindowListener experiment is getting some URI wrong. It seems like a good idea to check whether that is actually the case, i.e. to ensure that there's an actual document at that URI before using it.

**Comment by eyalroz** [comment]
@jobisoft : Have a look at the (yet untested) change. You challenged me to offer a PR, but before I test this out I want to know what you think about the idea.

**Comment by jobisoft** [comment]
To test and verify your changes, it is better you create a PR. You can change the PR at any time by just pushing changes to the branch and they will automatically become part of the PR.

First of all, do not use the word overlay anywhere :-)

My issue with this is, that it will do this check on each and every startup and the read is sycnhronous which means it has impact on the app startup time. I will accept this, if you make the test optional by some global debug flag, which than can also be used to supress all the console.logs which currently are in. In `getAPI` declare a `this.debug = true;` and use that and i will add a public method to set that via a call in background.js.

In `registerOptionsPage(optionsUrl)`  you need to check the final `self.pathToOptionsPage` and not the passed in optionsUrl.

How does that sound? Thanks for your contributions.

**Comment by eyalroz** [comment]
I'll probably get around to doing this tomorrow or early next week.

However... is there a way to determine whether an add-on was installed via the "debug add-ons" mechanism? That might spare us an explicit debug flag.

**Comment by jobisoft** [comment]
That ... is brilliant.
```
this.debug = context.extension.addonData.temporarilyInstalled;
```

**Comment by eyalroz** [comment]
So, it is a clever trick :-) ... but - it may not be obvious to authors that this is the way to check the validity of their URLs. If we use this approach, then it would need to be made quite clear at least in the wiki if not elsewhere.  Also, different behavior based on whether we're in debug mode might have other consequences. So on second thought I'm not entirely sure about this approach.

**Comment by jobisoft** [comment]
I full in favour of this.

**Comment by jobisoft** [comment]
merged.

**Comment by eyalroz** [comment]
Thanks. But - see my nitpicks on PR #39 .
