### ISSUE TITLE
Add an Add-On Preferences Submenu to the burger-menu as well

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#40]
At the moment, if an extensions registers an options page, the regular extension loader (WinodwListener) only adds an entry for the preferences in the Menu Bar's Tools | Addons submenu - not under "burger menu"/app menu's Add-Ons entry. See [Bugzilla issue 1662990](https://bugzilla.mozilla.org/show_bug.cgi?id=1662990).

@jobisoft says:

>  The hamburger menu seemed very different and I did not want to break anything so I did not try that.

but it is important for the preferences to be accessible from there as well, as users don't see the menu bar by default. So, please work with the TB developers to allow this overlaying/injection to happen robustly.

**Comment by jobisoft** [comment]
Reading the different bugs on BMO and thinking about it, I believe the better option is to change the WL to add its add-on option menu entry to the 3-dots menu in the add-on manager. This is where the options are now located and where future MailExtensions will have to be configuered. This way add-ons using the WL do not fall out of line and we reduce confusions, why not all add-ons show up in the "old" add-on options menu.

**Comment by jobisoft** [comment]
I will close this, as I will concentrate on the new approach with the 3dot menu in the add-ons tab.

**Comment by eyalroz** [comment]
Opened issue #41 .

However - it is important for me - and other authors I suppose - to not have to switch to the Add-On tab to get to the preferences. So, please consider re-opening this.

**Comment by jobisoft** [comment]
This will be a two step project. 

1. I will add it to the 3-dot menu, so I comply with the standard TB behaviour. 
2. If MailExtensions Options are added to the hamburger menu again, I will follow with the WL as well. I will try to lobby for that change in a new clean bug, but I ask you to not shoot in my knee by de-railing it towards the priviliges discussion, which is not getting us anywhere.

**Comment by eyalroz** [comment]
@jobisoft : Fair enough.
