### ISSUE TITLE
Make Add-On Preferences accessible through the "..." button in the Add-On tab

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#41]
At the moment, if an extensions registers an options page, the WinodwListener only adds an entry for the preferences in the Menu Bar's Tools | Addons submenu - but not through the extension's entry in the Add-On tab.

Since the Add-On tab is the central place for observing/managing one's extensions, and since WebExtensions with an unprivileged preferences page have those preferences accessible from the "..." menu in the Add-On tab entry, I suggest WL make that happen as well. Hopefully this can be done without help from within the Thunderbird code base itself, since such a suggestion has been met with rejection.

See also [Bugzilla issue 1662992](https://bugzilla.mozilla.org/show_bug.cgi?id=1662992).

**Comment by jobisoft** [comment]
Please stop calling it "regular extension loader". I created it. I name it. It's like calling my kid purposely with the wrong name, even after I corrected you.

I also came to the conclusion, that the WL should add itself there. I will see what I can do.

**Comment by eyalroz** [comment]
I'll oblige you, but when I talk to other people about it I need to call it by what it's used for. If I tell an extension author they can use a "WindowListener" for TB 78 compatibility, nobody understands what I want (without a long explanation). If I tell them they can use an "extension loader" for TB 78 compatibility they do understand.

**Comment by RealRaven2000** [comment]
+1 from me. I guess we could also overlay the code and hack that menu, but it would probably be ugly. I think having an xhtml dialog for options should be a "regular" usecase for mail extensions - they shouldn't be relegated to HTML content only.

**Comment by jobisoft** [comment]
XHTML is just another name for XUL and it will go away. XUL is dead and support for it is removed from M-C. We will get replacements for all XUL elements in HTML, as core needs them aswell. No panic.

**Comment by eyalroz** [comment]
@jobisoft : I'm 99% sure what RealRaven2000 meant is the ability to run proper chrome, with full privileges, in an extension's preference dialog (i.e. not XUL vs XHTML vs HTML).

**Comment by jobisoft** [comment]
Fixed in WL API 1.35. 

The options are now aligned to standard TB behavior to reduce user confusions:
68 -> in Tools -> Add-on options -> Options
78 -> in add-on manager -> ... menu -> Options
88 -> in add-on manager -> dedicated Options-Buttons

for 88 see https://bugzilla.mozilla.org/show_bug.cgi?id=1692616#c7
