### ISSUE TITLE
Typo at line 102 of 1.21 version of implementation.js and most of my URIs fail that check so addon doesn't run

### ISSUE THREAD

**Issue by smitgd** [thundernest/addon-developer-support#42]
Typo is "exits" should be "exists"

These items are logged:
```
console.log: WebExtensions: WindowListener API: Checking if document at <jar:file:///home/gene/78-copyfolder.xpi!/defaults/preferences/copyfolder.js> used in registration actually exits.
console.error: WebExtensions: 
  WindowListener API: Attempt to register non-existent default prefs script: jar:file:///home/gene/78-copyfolder.xpi!/defaults/preferences/copyfolder.js
(user provided script path was: defaults/preferences/copyfolder.js)
console.log: WebExtensions: WindowListener API: Checking if document at <chrome://copyfolder/content/copyfolder-prefs.xhtml> used in registration actually exits.
console.error: WebExtensions: 
  WindowListener API: Attempt to register non-existent options page: chrome://copyfolder/content/copyfolder-prefs.xhtml
console.log: WebExtensions: WindowListener API: Checking if document at <chrome://messenger/content/messenger.xhtml> used in registration actually exits.
console.log: WebExtensions: WindowListener API: Checking if document at <chrome://copyfolder/content/overlay-injectors/messenger.js> used in registration actually exits.
```
I put an additional self.log() line in the "catch" bracket and it appears that all the URIs are failing except chrome://messenger/content/messenger.xhtml.

Not sure but this might be related to this comment from the git log?:
```
Caveat: Currently FAILING for paths which are relative to the add-on's directory structure, SUCCEEDING for "chrome://" URLs
```
If I revert back to version 1.20 of imlementation.js, my addon runs OK.

The three exception errors all look like this:
```
22:24:06.879 [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: jar:file:///home/gene/78-copyfolder.xpi!/api/WindowListener/implementation.js :: aDocumentExistsAt :: line 105"  data: no] implementation.js:105:30
    aDocumentExistsAt jar:file:///home/gene/78-copyfolder.xpi!/api/WindowListener/implementation.js:105
    registerDefaultPrefs jar:file:///home/gene/78-copyfolder.xpi!/api/WindowListener/implementation.js:128
    registerDefaultPrefs self-hosted:1161
    result resource://gre/modules/ExtensionParent.jsm:948
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:489
    result resource://gre/modules/ExtensionParent.jsm:948
    callAndLog resource://gre/modules/ExtensionParent.jsm:910
    recvAPICall resource://gre/modules/ExtensionParent.jsm:947
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674 
```
The above information is not very helpful (to me) so this is what I added to print in the "catch" bracket to tell which URI the complaint is about:
```
console.log: WebExtensions: WindowListener API: bad uriString = <jar:file:///home/gene/78-copyfolder.xpi!/defaults/preferences/copyfolder.js>
console.log: WebExtensions: WindowListener API: bad uriString = <chrome://copyfolder/content/copyfolder-prefs.xhtml>
console.log: WebExtensions: WindowListener API: bad uriString = <chrome://copyfolder/content/overlay-injectors/messenger.js>
```

**Comment by jobisoft** [comment]
Will fix the typo. But I have issues reproducing the bug. When I set

```
  messenger.WindowListener.registerOptionsPage("chrome/content/addonoptions.xhtml")
```
in my background page, this URL is extended to a file ULR:

```
WindowListener API: Checking if document at <file:///C:/Users/John/Documents/GitHub/quicktext/chrome/content/addonoptions.xhtml> used in registration actually exits.
```

How did you get a `jar:file` in there? This entire check-url-code is only executed if the add-on is installed in debug mode (temporary install). 

What OS are you on?

Regarding the failing chrome:// path, are you sure, that you have called `registerChromeUrl()` before the `registerOptionsPage()` ?

Could you link to a repo of your code?

**Comment by smitgd** [comment]
>How did you get a jar:file in there? This entire check-url-code is only executed if the add-on is installed in debug mode (temporary install).

Not sure why it's called "jar" file. I just zipped the project to file 78-copyfolder.xpi
```
cd <git project directory on branch WL>
zip -r ../78-copyfolder.xpi *
```
This zips in some extraneous stuff like /.git. Would that matter? I'm also using the temporary install. Haven't tried a permanent install.

>What OS are you on?

Linux

>Regarding the failing chrome:// path, are you sure, that you have called registerChromeUrl() before the registerOptionsPage()?

I think so.
I tried to follow your 3-step guide for using WL. I also modeled my changes on Eyal's https://github.com/eyalroz/removedupes and he has helped me a lot via email.


> Could you link to a repo of your code?

It's now on branch "WL" here: https://github.com/smitgd/addon-copyfolder-tb-esr68/tree/WL

**Comment by jobisoft** [comment]
> This zips in some extraneous stuff like /.git. Would that matter? I'm also using the temporary install. 

Oh. You do not need to zip. When you select "temporary install", just select your manifest.json file. He will then load the add-on directly. A extra zip/xpi file is not needed. Is this fixing your issues?

**Comment by jobisoft** [comment]
You got a PR with some fixes. I can confirm, that URL check does not work if you use a XPI to install your add-on temporarily, but it works if you install "normal"

**Comment by smitgd** [comment]
Yes, it works fine with 1.21 when I install using manifest.json. Sorry, I'm completely new to this. 
(Also, FWIW, the zip ignores dot files so /.git is not included in the .xpi.)
I just tried a permanent (normal) xpi install so I can confirm that it works with v1.21 of implementation.js
Thanks!

**Comment by jobisoft** [comment]
Please check the WL repo regularly to see if it has been updated, so you can update your add-on (sadly that is a culprit of using external code).

**Comment by eyalroz** [comment]
@smitgd : Sorry, I should have probably updated to @jobisoft 's newer official version once it was out. I'll do that.

**Comment by smitgd** [comment]
> You got a PR with some fixes.

Thanks! I merged them and works OK.

> I can confirm, that URL check does not work if you use a XPI to install your add-on temporarily, but it works if you install "normal" without zipping it beforehand.

Not sure if this means my mistakes pointed to by the PR caused the problem. Tried again with the the PR merged and the newly zipped 78-copyfolder.xpi still prints errors and fails to run. But I guess running temporary with .xpi is not standard operating procedure and you should just run manifest.json.

**Comment by jobisoft** [comment]
@eyalroz : I actually think you had the same issue. Did you zip your add-on before you installed it temporarily?

**Comment by jobisoft** [comment]
> But I guess running temporary with .xpi is not standard operating procedure and you should just run manifest.json.

Yes. I didn't even know you could do that. It turns out, the code cannot check URLs if you zipped your add-on. I hope I can detect that and print a info message instead of the error.

**Comment by eyalroz** [comment]
> @eyalroz : I actually think you had the same issue. Did you zip your add-on before you installed it temporarily?

I always have and I continue to do so. Have not had this particular issue.

**Comment by eyalroz** [comment]
> I guess running temporary with .xpi is not standard operating procedure

It's very standard. If the user gets an XPI, the debugging-mode installation needs to be able to use that XPI.

**Comment by jobisoft** [comment]
Than I have to back out the patch.

**Comment by jobisoft** [comment]
Pull request #39 has been backed out, which solves this issue. The WL now only checks for built-in window URLs but not for documents provided by the add-on.

**Comment by eyalroz** [comment]
@jobisoft : Wait wait... with the PR as I first posted it, I wasn't seeing this error with my add-ons' XPIs. Doesn't that mean that some subsequent change broke this somehow?
