### ISSUE TITLE
Add-On Options/Preferences doubling

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#43]
Related to #25 :

Some of my users are complaining about getting a double "Add-On Options" menu - in TB 68 probably:

https://github.com/eyalroz/removedupes/issues/23

Could you reconsider your choice to not mess with the TB 68 menu? It would be quite helpful to users, who will no longer be annoyed by having to look in two places.

**Comment by jobisoft** [comment]
If you fix it, I will probably merge it. But we may not have any negative impact on TB68 itself.

**Comment by jobisoft** [comment]
Simplest approach would be to check [here ](https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js#L294) for the Thunderbird version, and if it is smaller than 78, skip the current code and just add the entry to the existing menu. Same goes for the removal section.

**Comment by ungeahnt** [comment]
Since the problem seems to be solved in V78, the request has been solved for me.  I will certainly update to V78 within the next weeks/months. You can close this issue if you like.
@eyalroz thanks a lot for this great add-on!

**Comment by jobisoft** [comment]
Fixed in WL API 1.35. 

The options are now aligned to standard TB behavior to reduce user confusions:
68 -> in Tools -> Add-on options -> Options
78 -> in add-on manager -> ... menu -> Options
88 -> in add-on manager -> dedicated Options-Buttons

for 88 see https://bugzilla.mozilla.org/show_bug.cgi?id=1692616#c7

**Comment by eyalroz** [comment]
So, in 68, it's in the existing menu item, right? No doubling?

**Comment by jobisoft** [comment]
yes. I just saw that TB may still show the "no add-on options found" entry, as it does not know about the WL entries. Maybe someone has some time to fix this.

**Comment by jobisoft** [comment]
The upcoming beta 87 needed special handholding as well, so I needed to update again. This update also includes a fix for the 68 issue with the "no add-on options found" entry.
