### ISSUE TITLE
Please update the WindowListener API tutorial

### ISSUE THREAD

**Issue by ejs-ejs** [thundernest/addon-developer-support#44]
In the introduncion on 'background.js'
 ```
messenger.WindowListener.registerWindow(
    "chrome://messenger/content/messenger.xul", ...)
``` must be 
```
messenger.WindowListener.registerWindow(
    "chrome://messenger/content/messenger.xhtml", 
``` 
I'm still unable to load the extension, but it' because on extension must have icons (line 327 of the 'implementation.js')?

**Comment by jobisoft** [comment]
If you follow the tutorial, then you will be in TB68 at that step, which needs `*.xul`.

Only in the last step, you switch to `*.xhtml`, which is explained here:
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Finalizing

I will add an info, that images are required.

**Comment by ejs-ejs** [comment]
Got it. I must work on TB 78.3.1, as I'm too late for 68.*

**Comment by jobisoft** [comment]
I really (!) suggest to go back to TB68 and do the tutorial in Tb68. You can install it again in a dedicated folder, disable internet before you fire that up so it does not get autoupdated and disable auto update in the settings.

**Comment by jobisoft** [comment]
I updated the guide and made icon mandetory:
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisteroptionspage

**Comment by ejs-ejs** [comment]
No way. It would be too easy :)
![thunderbird_pSfE5vmRBo](https://user-images.githubusercontent.com/14044646/95627428-e3476580-0a84-11eb-958c-6730fb2305c9.png)

**Comment by eyalroz** [comment]
@ejs-ejs : I second @jobisoft's recommendation. Switch to WindowListener in TB 68, get it working, then apply the 68->78 changes. Spare yourself headache and heartache...

**Comment by ejs-ejs** [comment]
Storry so far: I can add a localized context menu item.
