### ISSUE TITLE
Read Thunderbird settings value for add-on

### ISSUE THREAD

**Issue by devmount** [thundernest/addon-developer-support#45]
Is there any way to access the Thunderbird settings? I created the [ThirdStats add-on](https://github.com/devmount/third-stats) and got the request (https://github.com/devmount/third-stats/issues/72) to provide an option to choose, on which day the week should start. This setting already exists in Thunderbirds calendar settings, so is there any way to use this value in an add-on?
Thanks!

**Comment by jobisoft** [comment]
I updated the LegacyPrefs API to get that settings. In the long run, this setting should be provided by the new calendar API. As long as we do not have that, use the LegacyPrefs API:

`messenger.LegacyPrefs.getPref("calendar.week.start");`

https://github.com/thundernest/addon-developer-support/tree/master/auxiliary-apis/LegacyPrefs

**Comment by eyalroz** [comment]
Doesn't seem to work for getComplexValue, and in particular - localized strings.

**Comment by jobisoft** [comment]
Never used getComplexValue. Do you have details? Regarding localized strings, that issue (https://github.com/thundernest/addon-developer-support/issues/6) stalled. Do you have any insights you could share?

**Comment by devmount** [comment]
@jobisoft It's working, thank you very much for your fast answer and solution! 👏🏻
