### ISSUE TITLE
Retrieve color scheme of active theme

### ISSUE THREAD

**Issue by devmount** [thundernest/addon-developer-support#46]
I'd like to provide a light or dark color scheme in my add-on according to the users activated TB theme. Is there any way to retrieve the information, which color scheme the user currently uses?

**Comment by jobisoft** [comment]
The issue section is mainly if you find bugs in the content of this repo or wiki. 

Please post support questions in our topicbox:
https://thunderbird.topicbox.com/groups/addons

**Comment by devmount** [comment]
Sorry, will do. Thanks!
