### ISSUE TITLE
Help to identify registerShutdownScript is needed

### ISSUE THREAD

**Issue by benjaminrein** [thundernest/addon-developer-support#48]
Hi, 

I just started to try updating the gcontactsync add-on, which doesn't work any more since TB 78. 

Could you please provide more information on how to identify code which is relevant for registerShutdownScript? Just something to search for in the existing code for each of the most used stuff would be great. This would be as well reduce the time experienced addon developers need for the migration.

E.g. to find autocomplete components I searched for "Components.interfaces.nsIComponentRegistrar", but don't know if the search criteria is suitable.

Documentation I'm referring to:
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregistershutdownscript

Is anything available to easily get the remaining not properly unloaded stuff from within a debugging session inside TB?
Thanks for your help.

Regards
Benjamin

**Comment by jobisoft** [comment]
I do not have a complete list, as there are so many things a legacy add-on could do. You will "learn" of such things, when you reload your add-on and redoing such registerings will produce errors. Or if you unload your add-on and you will still see errors in the console which look like they come from your code.

Try to minimize your search, just search for `nsIComponentRegistrar`.

Other things are `addObserver` calls. They have to be removed by `removeObserver` calls. Same goes for `addEventListener` calls.

Not all such things have to be unloaded in the global shutdown script. If something is registered in the onload of a window, then it should be unloaded in that windows unload directly.
