### ISSUE TITLE
Bootstrap.js is cached

### ISSUE THREAD

**Issue by vanowm** [thundernest/addon-developer-support#49]
How do we test our development without restarting the application?

I'm loading temporary extension, than do changes to bootstrap.js file, hit reload button, but the changes are not visible until I restart thunderbird. I wouldn't mind restarting it if I didn't have to manually load temporary addon each time..

(referring to guide https://github.com/thundernest/addon-developer-support/wiki/Using-the-BootstrapLoader-API-to-convert-a-Legacy-Bootstrap-WebExtension-into-a-MailExtension-for-Thunderbird-78)

**Comment by jobisoft** [comment]
I will check. Can you post a link to your work so I can reproduce your issue?

**Comment by vanowm** [comment]
I'm using a blank extension, with bare minimum.

So far using cachingfix experiment seems to work:
https://github.com/rsjtdrjgfuzkfg/thunderbird-experiments/tree/master/experiments/cachingfix

**Comment by jobisoft** [comment]
Thanks for your feedback. I did implement something like cachingfix into the other wrapper (windowListener), but not into the BoostrapLoader. I will recheck my considerations here.

**Comment by jobisoft** [comment]
Released v1.3, which flushes caches. Could you verify, that it works now without cachingfix?

**Comment by vanowm** [comment]
Thank you. 
In v1.3 changes in bootstrap.js now reflected immediately after reload.
