### ISSUE TITLE
Need explanation of what addon "shutdown" is

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#5]
Many/most add-on authors have never had to support "shutting down" their add-on. The add-on was simply assumed to just run, and if something needs to be shut down - it was TB's business. Now, there's a
`WindowListener.registerShutdownScript()` which calls some code of ours.

We need an explanation for when / under what circumstances this occurs. Also, can we really register custom XPCOM objects? Haven't all of those gone away? Perhaps a link to an example would help (e.g. something which needs some work at shutdown.)

**Comment by jobisoft** [comment]
I made changes, which I think cover your remarks.

**Comment by jobisoft** [comment]
Closing this, to have it out of the way. Reopen if needed.
