### ISSUE TITLE
'openDialog' called with a non-literal uri

### ISSUE THREAD

**Issue by vanowm** [thundernest/addon-developer-support#50]
AMO is issuing a warning when submitting bootstrap addon:

> 'openDialog' called with a non-literal uri
> 
> Warning: Calling 'openDialog' with variable parameters can result in potential security vulnerabilities if the variable contains a remote URI. Consider using 'window.open' with the 'chrome=no' flag.
> api/BootstrapLoader/implementation.js line 173 column 94

Don't think it's an issue, just though you should know.

**Comment by jobisoft** [comment]
Yup, I that is the added support for optionsPage in v1.4 and that URI is constructed from a value defined in background.js. This is checked for during review and as it is dynamic but fixed (the user cannot change it), it is not an issue.
