### ISSUE TITLE
small typo in example codes in Wiki tutorial WindowListener API: Getting Started

### ISSUE THREAD

**Issue by caligraf** [thundernest/addon-developer-support#51]
There is a missing ']' at the end in :
`messenger.WindowListener.registerChromeUrl([ `
`  ["content",  "quicktext",           "chrome/content/"],`
`  ["resource", "quicktext-shared",    "chrome/skin/shared/"],`
`  ["resource", "quicktext",            osResourcePath ],`
`  ["locale",   "quicktext", "en-US",  "chrome/locale/en-US/"],`
`  ["locale",   "quicktext", "ca",     "chrome/locale/ca/"],`
`  ["locale",   "quicktext", "de",     "chrome/locale/de/"],`
`  ["locale",   "quicktext", "es-MX",  "chrome/locale/es-MX/"],`
`  ["locale",   "quicktext", "es",     "chrome/locale/es/"],`
`  ["locale",   "quicktext", "fr",     "chrome/locale/fr/"],`
`  ["locale",   "quicktext", "hu-HU",  "chrome/locale/hu-HU/"]`
**]**`);`
and a missing ',' after /icon16.png" in 
`"icons": {`
`    "16": "content/skin/icon16.png"`**,**
`    "32": "content/skin/icon32.png"`
`  }`

**Comment by jobisoft** [comment]
Thanks for reporting. Can you check if I fixed it correctly?

**Comment by caligraf** [comment]
It is ok now
