### ISSUE TITLE
injectElements does not merge attributes of existing elements

### ISSUE THREAD

**Issue by tipichris** [thundernest/addon-developer-support#53]
It looks as if when injectElements finds and existing element, it cycles through and inserts its children. But it does not merge attributes of the element itself. Consequently not all XUL overlays are handled as expected.

Example:
My addon turns phone numbers in the address book into clickable links. The overlay includes this

```
<description id="cvPhCellular" onclick="tbdialout.onLinkClickDial('CellularNumber')" tooltiptext="&tbdialoutToolbarCell.tooltip;" class="CardViewLink tbdialout-phone-number-link" />
```

But including this overlay snippet in the argument to injectElements has no effect.

**Comment by jobisoft** [comment]
You will have to get that element via getElementById and update it as you need it. injectElement is not a full replacement for the old overlayloader. For example keeping track of all modified attributes will require much more code, but I want to keep the code as simple as possible.

So this is a wontfix and you have to do it manually and also remove your attributes manually on unload. Do you need further help with that?

**Comment by tipichris** [comment]
Yes please! And many other things (especially localisation)!

I have managed to set the attributes by using el.setAttribute() in the function that is initially called by onLoad from the script given as second argument to registerWindow. Is removing them as simple as calling el.removeAttribute() in the unLoad script?

**Comment by tipichris** [comment]
And now I think that through I guess I need to keep track of what the attributes were before I messed with them, especially class, and make sure I put them back the same.

**Comment by jobisoft** [comment]
Looking at the first comment: 
* Do not use the onclick attribute but use addEventListener() to attach a click event handler which you remove upon unload.
* For the class use ` element.classList.add("mystyle")` and `element.classList.remove("mystyle")`. 

No need to mess with attributes at all.

**Comment by tipichris** [comment]
Thanks, I'll work on that. Can I beg your help with localization? I'm really struggling to understand how to make extension, or messenger, available within scripts. The script that is loaded by my options page XHTML, for example. Adding an event listerner to run i18n.updateDocument() just throws an error about messenger not being defined.

**Comment by jobisoft** [comment]
Can we move this to https://thunderbird.topicbox.com/groups/addons ? Just post your question there.
