### ISSUE TITLE
WindowsListener support for localized preferences

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#6]
I'm looking at [`wrapper-apis/WindowListener/implementation.js`](https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js), in the [code for the preference-handling anonymous function at L56](https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js#L56), and am seeing cases for charpref, intpref, and boolpref - but not for localized string preferences i.e. the preferences you get with:
```
Cc["@mozilla.org/preferences-service;1"]
    .getService(Components.interfaces.nsIPrefBranch)
    .getComplexValue("what.ever",Components.interfaces.nsIPrefLocalizedString).data;
```
will the WindowListener work with those?

**Comment by jobisoft** [comment]
In your injected Javescript, you can do whatever is supported by TB78 core. A quick check on searchfox.org shows lots of usage in core, so I think that should still work. If your question was about the defaults pref handling, I do not know if localized prefs could have defaults and how they are set. I would need to see such a prefs.js file from a TB68 AddOn.

**Comment by eyalroz** [comment]
Here's how you set them:
```
var prefService = 
  Cc["@mozilla.org/preferences-service;1"]
    .getService(Components.interfaces.nsIPrefBranch);
var pls = 
  CC["@mozilla.org/pref-localizedstring;1"]
    .createInstance(Components.interfaces.nsIPrefLocalizedString);
pls.data = get_the_value_somehow();
prefService.setStringPref("what.ever.pref.name", pls);
```
TBH, I only ever _read_ one of these, and never set one of my own. I'm not even sure it needs to be localized; it's `"mailnews.view_default_charset"`.

**Comment by jobisoft** [comment]
You can do that in the currently  undocumented startup script, I think via registerStartupScript(). It would be interesting for me, if the defaults pref file supported a special syntax for these, which I would have to add to my parser. So if you ever come across such a preference.js file...

**Comment by ejs-ejs** [comment]
Is it possible to make more code samples on the current localization system? I could not grasp it quickly and there are little plugins to study from. The 
```
var myapi = class extends ExtensionCommon.ExtensionAPI {
 
 getAPI(context) {
    let extension = context.extension;
    ... 
  }
}
```
made me mad :)

**Comment by eyalroz** [comment]
@ejs-ejs : Open a different issue about that please.

**Comment by jobisoft** [comment]
Did not receive an actual use case in tha last 9 month. Closing.
