### ISSUE TITLE
WindowListener API: can not access background page and other experiment APIs anymore

### ISSUE THREAD

**Issue by int-red** [thundernest/addon-developer-support#60]
Using the WindowListener API I made an extension which adds the nsIMsgSendListener to the compose window.
Goal was to intercept an email when it was sent and then load it from the Sent-folder to do some further processing with it.

This worked quite well so far in TB 68.12.1 but not in TB 78.8.0 anymore.

This is how I registered WL in TB 68
`messenger.WindowListener.registerWindow(
	"chrome://messenger/content/messengercompose/messengercompose.xul",
	"chrome://dbmail/content/scripts/messengercompose.js");
`
but in TB 78.8 messengercompose.xul does not exist anymore so I changed it to
`messenger.WindowListener.registerWindow(
	"chrome://messenger/content/messengercompose/messengercompose.xhtml",
	"chrome://dbmail/content/scripts/messengercompose.js");
`
this made the JavaScript Injection work again, but in the injected code I need access to the background page and other experiment apis.
In TB 68 I could access the backgroundpage like this:
`var bgpage = WL.messenger.extension.getBackgroundPage();`
but in TB 78 this gives the error "TypeError: WL.messenger.extension.getBackgroundPage is not a function"

Other experiment apis like my "dbsend" api I could access like this:
`WL.messenger.dbsend.GetMessageHeader(gDBsendMsgID, gDBsendFolderURI)`
but in TB 78 this gives the error "TypeError: WL.messenger.dbsend is undefined"

**Comment by jobisoft** [comment]
Which version of the WL are you using?

**Comment by int-red** [comment]
I am using the latest version 1.39

**Comment by jobisoft** [comment]
You need to add some voodoo. getBackgroundpage no longer works and I removed the "true" messenger object from the WL.

There is a fake one now:
https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js#L291

1. Try to not call APIs from your Experiment. Refactor your code so you only call from WebExtension context into your Experiment, not the other way around. (Really! The WL may break beyond repair for later verisons of TB)
2. If you really need to call specific APIs, you need to add them to getMessenger().

**Comment by int-red** [comment]
Thank you for your quick responses.

> Try to not call APIs from your Experiment. Refactor your code so you only call from WebExtension context into your Experiment, not the other way around. (Really! The WL may break beyond repair for later versions of TB)

But somehow I need to get the information that I get from the nsIMsgSendListener, which is executed in the WindowListener, back into the WebExtension context.
So far I opened a new tab from the nsIMsgSendListener onGetDraftFolderURI callback function in the WindowListener context which I filled with the information that I get from the nsIMsgSendListener.

How would you transfer data from the WindowListener back into the WebExtension context?

**Comment by jobisoft** [comment]
Is your repo public, so I can have a look?

sIMsgSendListener sound like it would fit to be an event, so you would need to write your own experiment that creates an event which notifies your WebExtension when sIMsgSendListener got something. You can send strings back to your webExtension, but if you need to manage a more complex object, you would need to track those in the experiment and give them ids and send back the id. Whenever your webextension wants to do something with such an object, it needs to use that id and your Experiment look sup the actual object.

https://webextension-api.thunderbird.net/en/78/how-to/experiments.html#implementing-events

If I can look at code, I might be of greater help.

John

**Comment by int-red** [comment]
Thank you very much for your work. I think this this ping-pong based messaging system will be helpful for many addon developers.

For my issue your hint to the Experiment API events was enough.
With this I was able to implement what I need - it is an additional compose API event which gets called when the mail was sent and copied to the sent folder. I called it "onAfterSend".

I published my code here:
https://github.com/int-red/experiment-api-composeevent

I would be glad if you could review it and give me some feedback on things that could be improved.

I recognized two strange behaviours/bugs while testing it (I used Thunderbird 78.8.1)
1. When 'Message Synchronizing' is deactivated for the Sent folder and I try to open the message with the messageId I got from the "onAfterSend" event using messenger.messages.getFull I get this exception: `[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgMessageService.streamMessage]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/gloda/MimeMessage.jsm :: MsgHdrToMimeMessage :: line 236"  data: no] MimeMessage.jsm:236:16
    MsgHdrToMimeMessage resource:///modules/gloda/MimeMessage.jsm:236
    getFull chrome://messenger/content/parent/ext-messages.js:212
    getFull chrome://messenger/content/parent/ext-messages.js:210
    getFull self-hosted:844
    result resource://gre/modules/ExtensionParent.jsm:996
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:602
    result resource://gre/modules/ExtensionParent.jsm:996
    callAndLog resource://gre/modules/ExtensionParent.jsm:958
    recvAPICall resource://gre/modules/ExtensionParent.jsm:995
    AsyncFunctionNext self-hosted:693
`
2. The second and much stranger behaviour: When the Sent folder is selected in the folder pane of the main mail view while I compose and send a mail and then I try to get the messageheader for the messageId I got from the "onAfterSend" event using messenger.messages.get(messageId) then the returned messageheader is always null.

**Comment by jobisoft** [comment]
Great! Yes, the WL API was only a quick start to get addons converted fast for TB78, but in the end everybody has to move forward to something like you are having now.

I will have a look at your code shortly and comment in your own repo.
