### ISSUE TITLE
NotifyTools: notifyTools.js throws error when 'inside' WindowListener

### ISSUE THREAD

**Issue by nkgm-bs** [thundernest/addon-developer-support#62]
When notifyTools.js is included in a WindowListener add-on it throws

`window is not defined`

at notifyTools.js:115 (Version 1.3)

**Comment by jobisoft** [comment]
Can you check if you have this already?
https://github.com/thundernest/addon-developer-support/blob/master/scripts/notifyTools/notifyTools.js#L114

Maybe I messed up the version numbers at one point? I thought I fixed that by checking for window....

**Comment by nkgm-bs** [comment]
Yes, the error really happens in the 'if (window) {' line

**Comment by jobisoft** [comment]
Could you send me an add-on which triggers this error? I cannot reproduce this here. Which version of TB?

**Comment by nkgm-bs** [comment]
TB version is 78.10.1
And i can't send you the add-on. Its Cardbook where i injected notifyTools in a local copy to implement a communication with my 'Simple Mail Redirect'. I have another small add-on which uses WindowListener and i will try to reproduce the problem there.

**Comment by nkgm-bs** [comment]
Here's a very short add-on which essentially does nothing expect triggering the error, at least on my computer (Windows 10)
[Info_test.zip](https://github.com/thundernest/addon-developer-support/files/6429777/Info_test.zip)

**Comment by jobisoft** [comment]
OK, window was null in my test cases and undefined in yours. I could either put a try catch around the whole thing or explicitly test for undefined. Can you check if the proposed fix is working for you?
https://github.com/thundernest/addon-developer-support/commit/d425d88156a05c6372a448daa5bc8e89aeefdbc6

**Comment by nkgm-bs** [comment]
Yes, this fixes it.
Thanks
