### ISSUE TITLE
TypeError: element.contentWindow is null

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#65]
When I try to load my [removedupes](https://github.com/eyalroz/removedupes) extension with the regular extension loader (WindowsListener), v1.56, on TB 90.0b3, I get the following errors:

```
TypeError: element.contentWindow is null 2 implementation.js:512:11
    _unloadFromWindow jar:file:///home/eyalroz/.thunderbird/hvz7emjt.default-beta/extensions/{a300a000-5e21-4ee0-a115-9ec8f4eaa92b}.xpi!/api/WindowListener/implementation.js:512
    onUnloadWindow jar:file:///home/eyalroz/.thunderbird/hvz7emjt.default-beta/extensions/{a300a000-5e21-4ee0-a115-9ec8f4eaa92b}.xpi!/api/WindowListener/implementation.js:339
    checkAndRunExtensionCode resource:///modules/ExtensionSupport.jsm:225
    _checkAndRunMatchingExtensions resource:///modules/ExtensionSupport.jsm:195
    _addToListAndNotify resource:///modules/ExtensionSupport.jsm:175
```
... although this is after several errors complaining about my manifest.json, e.g.:
```
Error while loading 'jar:file:///home/eyalroz/.thunderbird/hvz7emjt.default-beta/extensions/%7Ba300a000-5e21-4ee0-a115-9ec8f4eaa92b%7D.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:614
    readJSON resource://gre/modules/Extension.jsm:614
    onStopRequest resource://gre/modules/NetUtil.jsm:128
```

**Comment by jobisoft** [comment]
stop calling it regular extension loader

**Comment by jobisoft** [comment]
Which add-on of yours is it? I updated Remove Dupes to use the latest WL API and it works without issues on 90.0b3 (32-Bit). Could you attach the XPI you are using, which fails?

**Comment by eyalroz** [comment]
[You say Tom*ai*to, I say tom*ah*to](https://www.youtube.com/watch?v=G2wkO0DhpEY)

**Comment by eyalroz** [comment]
Ok, somehow it started working, I'm not sure why. Maybe I zipped the wrong files together? :-(

I guess I'll close this for now. Sorry for the bother.
