### ISSUE TITLE
WL API addons have a (unwanted?) link on the title in addons manager

### ISSUE THREAD

**Issue by ThunderbirdMailDE** [thundernest/addon-developer-support#66]
In Thunderbird Daily and 91 Beta the addons have a link on their title in addon manager:

![addon-link](https://user-images.githubusercontent.com/47142502/126492951-d1a7b6bb-99ca-4940-a705-d3a34602d265.png)

**Comment by jobisoft** [comment]
Global bug and fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1707503
