### ISSUE TITLE
Support registering multiple  overlays with a single command

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#67]
At the moment, an extension needs to make a separate `WindowListener.registerWindow()` call for every overlay injector it wishes to apply. This, while chrome URL registration can be done with an array of multiple entries, passed to a single `WindowListener.registerChromeUrl()` call.

We should be able to write:
```
WindowListener.registerWindow([
  [ target_1, injector_script1 ],
  [ target_2, injector_script2 ],
  [ target_3, injector_script3 ],
]);
```

**Comment by eyalroz** [comment]
Sorry for the repeat...

**Comment by jobisoft** [comment]
The wrapper APIs have been deprecated and will not receive further updates:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis
