### ISSUE TITLE
Debugging RFE: Support checking if injected elements persist

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#68]
In some cases, TB removes/deletes, or maybe even moves, elements injected into DOM documents. A recent painful example seems to be toolbar buttons, but there may be other cases where part of the UI is regenerated for some reason.

It would be useful if, as a debugging feature, WL could set some timeout, after which it checks and reports whether some/all/any of the injected elements still exist where they have been injected.

**Comment by jobisoft** [comment]
The wrapper APIs have been deprecated and will not receive further updates:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis
