### ISSUE TITLE
Debugging RFE: Detect invalid chrome URLs

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#69]
An extension's `background.js`  may make `messenger.WindowListener.registerWindow()` calls with a `windowHref` which is invalid, e.g. misspelled, without an appropriate prefix etc. It would be useful if WL could report that it is unable to carry out the registerWindow (if that is at all possible to determine).

**Comment by jobisoft** [comment]
iirc, it does that if the add-on is installed as temporary.
https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js#L472

**Comment by eyalroz** [comment]
But shouldn't the debug parameter of `injectElements()` control whether or not that's checked and reported?

**Comment by jobisoft** [comment]
Those are two different things. The debug parameter of `injectElements()` enables verbose debug output regarding injecting actual elements into a window and is executed inside injector scripts. 

IIRC, it is way to late to determine, if the injector script itself could be linked to an XHTML file. If the linked XHTML file does not exist, the injector script is never executed and therefore its calls to `injectElements()` never run and therefore cannot report anything.

**Comment by eyalroz** [comment]
> f the linked XHTML file does not exist, the injector script is never executed and therefore its calls to injectElements() never run and therefore cannot report anything.

But, when we `registerWindow()`, can you not determine whether the XHTML file exists or not?

**Comment by jobisoft** [comment]
I do, but only when installed temporarly during development. The check is skipped if installed as a full add-on, so devs do not have to use a debug=true, variable, which they might forget to remove when released. I think that was a request from a developer, actually.

**Comment by jobisoft** [comment]
You could make a PR, adding a third optional paramter to `registerWindow()` to enforce the check.
