### ISSUE TITLE
Arrange it so that multiple files can be registered for each window

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#7]
When registering "overlays" using the WindowListener, currently,

> Each window URL may only be registered once and for each window URL only one JavaScript file may be registered. If you had defined multiple overlays and/or styles for the same window URL, you have to load all those items from the injected JavaScript file now 

Instead, the WindowListener should accept multiple "overlays" registered for every window URL. 

The "minimum" would be separate JS files - so that we can separate our injections for each of what used to be our separate files.

But actually, the WindowListener can easily do the injection of non-injector script files itself (i.e. execute the `Services.scriptloader.loadSubScript()` calls), and the same goes for injecting CSS files.

As for XUL files - this is probably more difficult of a task, but I wonder if the "XUL overlay loader" which apparently existed in v68 can't just be run still. If it can - that means all injections can be automated. As authors, all we would need to ensure is that the namespace is used throughout. 

(and if all injections can be automated - then why can't they just be picked up directly for a `chrome.manifest` file instead of being spelled out in `background.js`?)

**Comment by jobisoft** [comment]
I explained in one of the other issues, that it is a design decission of the WindowsListener API to allow only one js file per window. I will not change that. You can use that js file as a "loader" and load all your individual files. Closing this, as the XUL discussion has also been started somewhere else.
