### ISSUE TITLE
Report error when trying to inject XUL/XHTML not intended to be a root element

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#71]
When one tries to inject some XUL/XHTML code, it either gets inserted/added to existing elements in the document, or - if relevant elements aren't found - added as independent children of the root IIANM. 

While this is indicated in debugging mode, I believe effort could and should be made to detect cases where the XUL/XHTML elements were intended to be added to existing ones, and those targets were not found.

This can be done by:

* The user saying so explicitly, e.g.:
   *  another argument to `injectElements()`
   * a sister method with a different name, say `injectIntoExistingElements()` or whatever
* WL detecting the indication of this by considering insertafter and insertbefore text (and whether they can be satisfied by the injected XUL/XHTML itserlf).

if WL realizes that the hierarchy of elements mustn't be a separate child of the document root - it should log an error to the console (regardless of debug settings).

**Comment by jobisoft** [comment]
There will be no further resources spend on the WindowListener API.

**Comment by eyalroz** [comment]
Why? Extensions are important.

**Comment by RealRaven2000** [comment]
> Why? Extensions are important, and extension loading is an important part of extension support.

Because there is no budget for it? You can every easily fork and branch WindowListener and create your own custom version. If you think logging this detail is important, I can help you with that? 
(Disclaimer: I am not paid by Mozilla / Thunderbird, just a fellow experimental Add-on Dev)

**Comment by eyalroz** [comment]
> Because there is no budget for it?

No, that's a reason why a bug might stay open and not get resolved for a while. And then the text would be "Note that none of my time is being allocated to do work on this".

**Comment by jobisoft** [comment]
The wrapper APIs have been deprecated and will not receive further updates:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis
